=== dnguyen09/solvd-laba-data-base/src/main/resources/xml/OlympicData.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="olympicData">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="hostCountry">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hostCountryId" type="xs:int"/>
                            <xs:element name="countryName" type="xs:string"/>
                            <xs:element name="continent" type="xs:string"/>
                            <xs:element name="capitalCity" type="xs:string"/>
                            <xs:element name="yearOfHost" type="xs:gYear"/>
                            <xs:element name="InternationalOlympicCommitee">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="iocId" type="xs:int"/>
                                        <xs:element name="iocName" type="xs:string"/>
                                        <xs:element name="president" type="xs:string"/>
                                        <xs:element name="headQuater" type="xs:string"/>
                                        <xs:element name="yearEstablished" type="xs:int"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="city">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cityId" type="xs:int"/>
                            <xs:element name="cityName" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="athlete">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="athleteId" type="xs:int"/>
                            <xs:element name="athleteName" type="xs:string"/>
                            <xs:element name="gender" type="xs:string"/>
                            <xs:element name="age" type="xs:int"/>
                            <xs:element name="Team">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="teamId" type="xs:int"/>
                                        <xs:element name="teamName" type="xs:string"/>
                                        <xs:element name="nation">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nationId" type="xs:int"/>
                                                    <xs:element name="nationName" type="xs:string"/>
                                                    <xs:element name="region" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="hotel">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="hotelId" type="xs:int"/>
                                                    <xs:element name="hotelName" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="event">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="eventId" type="xs:int"/>
                            <xs:element name="eventName" type="xs:string"/>
                            <xs:element name="startDate" type="xs:date"/>
                            <xs:element name="endDate" type="xs:date"/>
                            <xs:element name="sport">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="sportId" type="xs:int"/>
                                        <xs:element name="sportName" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="location">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="locationId" type="xs:int"/>
                                        <xs:element name="locationName" type="xs:string"/>
                                        <xs:element name="capacity" type="xs:int"/>
                                        <xs:element name="City">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="cityId" type="xs:int"/>
                                                    <xs:element name="cityName" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="teams">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="team" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="teamId" type="xs:int"/>
                                                    <xs:element name="teamName" type="xs:string"/>
                                                    <xs:element name="Nation">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nationId" type="xs:int"/>
                                                                <xs:element name="nationName" type="xs:string"/>
                                                                <xs:element name="region" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dnguyen09/solvd-laba-data-base/src/main/resources/xml/OlympicData.xml
<?xml version="1.0" encoding="UTF-8"?>
<olympicData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="OlympicData.xsd">
    <hostCountry>
        <hostCountryId>1</hostCountryId>
        <countryName>United Kingdom</countryName>
        <continent>Europe</continent>
        <capitalCity>London</capitalCity>
        <yearOfHost>2012</yearOfHost>
        <InternationalOlympicCommitee>
            <iocId>1</iocId>
            <iocName>International Olympic Commitee</iocName>
            <president>Thomas Bach</president>
            <headQuater>Lausanne, Switzerland</headQuater>
            <yearEstablished>1894</yearEstablished>
        </InternationalOlympicCommitee>
    </hostCountry>
    <city>
        <cityId>1</cityId>
        <cityName>London</cityName>
    </city>
    <athlete>
        <athleteId>1</athleteId>
        <athleteName>Jordan Williams</athleteName>
        <gender>male</gender>
        <age>23</age>
        <Team>
            <teamId>1</teamId>
            <teamName>Athletic Team</teamName>
            <nation>
                <nationId>1</nationId>
                <nationName>Australia</nationName>
                <region>Oceania</region>
            </nation>
            <hotel>
                <hotelId>1</hotelId>
                <hotelName>Grand Plaza</hotelName>
            </hotel>
        </Team>
    </athlete>
    <event>
        <eventId>1</eventId>
        <eventName>Parallel Bars</eventName>
        <startDate>2012-07-14</startDate>
        <endDate>2012-07-15</endDate>
        <sport>
            <sportId>1</sportId>
            <sportName>Athletics</sportName>
        </sport>
        <location>
            <locationId>1</locationId>
            <locationName>Olympic Stadium</locationName>
            <capacity>80000</capacity>
            <City>
                <cityId>1</cityId>
                <cityName>London</cityName>
            </City>
        </location>
        <teams>
            <team>
                <teamId>1</teamId>
                <teamName>Athletic Team</teamName>
                <Nation>
                    <nationId>1</nationId>
                    <nationName>Australia</nationName>
                    <region>Ocenia</region>
                </Nation>
            </team>
            <team>
                <teamId>2</teamId>
                <teamName>Basketball Team</teamName>
                <Nation>
                    <nationId>10</nationId>
                    <nationName>Denmark</nationName>
                    <region>Northern Europe</region>
                </Nation>
            </team>
        </teams>
    </event>
</olympicData>
